### ISSUE TITLE
additional output

### ISSUE THREAD

**Issue by mas12498** [caseyshields/Orion#6]
Would like a file output generation capability for testing against other reference star tracking sources... perhaps .csv formatted that contains:
UTC date-time, localAZ, localEL, RefractDeltaEL

or some such format for a run against a selected star number from a specified location geodetic Lat, Geodetic Lon, Geodetic height at a specified message rate from a specified start time for a specified duration.

**Comment by caseyshields** [comment]
added report command to orion client
